local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   update_frequency: 15.0
   publish_frequency: 5.0
   width: 8.0
   height: 8.0
   resolution: 0.1
   static_map: false
   rolling_window: true
   obstacle_range: 2.5
   raytrace_range: 3.0
   transform_tolerance: 0.5

   plugins:
   - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

   inflation_layer:
      enabled: true
      cost_scaling_factor: 5.0
      inflation_radius: 0.31